=== JazminWhy/olympics/data/mappings/20181025_TargetXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://wdi.org/Project/OlympicDataIntegration" elementFormDefault="qualified" xmlns="https://wdi.org/Project/OlympicDataIntegration" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="WinningAthletes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Athlete" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ID" type="xs:string"/>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Birthday" minOccurs="0" maxOccurs="1" type="xs:date"/>
							<xs:element name="PlaceOfBirth" minOccurs="0" maxOccurs="1" type="xs:string"/>
							<xs:element name="Sex" minOccurs="0" maxOccurs="1" type="xs:string"/>
							<xs:element name="Nationality" minOccurs="0" maxOccurs="1" type="xs:string"/>
							<xs:element name="Weight" minOccurs="0" maxOccurs="1" type="xs:string"/>
							<xs:element name="Height" minOccurs="0" maxOccurs="1" type="xs:string"/>
							<xs:element name="OlympicParticipations" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="OlympicParticipation" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="P-ID" type="xs:string"/>
													<xs:element name="Year" minOccurs="0" maxOccurs="1" type="xs:integer"/>
													<xs:element name="Season" minOccurs="0" maxOccurs="1" type="xs:string"/>
													<xs:element name="City" minOccurs="0" maxOccurs="1" type="xs:string"/>
													<xs:element name="OlympicTeam" minOccurs="0" maxOccurs="1" type="xs:string"/>
													<xs:element name="Disciplines" minOccurs="0" maxOccurs="1" type="xs:string"/>
													<xs:element name="Event" minOccurs="0" maxOccurs="1" type="xs:string"/>
													<xs:element name="Medal" minOccurs="0" maxOccurs="1" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JazminWhy/olympics/data/mappings/Output/20181027_Gymnasts_Final.xml
<?xml version="1.0" encoding="UTF-8"?>
<WinningAthletes xsi:schemaLocation="https://wdi.org/Project/OlympicDataIntegration 20181025_TargetXML.xsd" xmlns="https://wdi.org/Project/OlympicDataIntegration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Athlete>
		<ID>G-100001</ID>
		<Name>georgia bonora</Name>
		<Birthday>1990-05-19</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100002</ID>
		<Name>ashleigh brennan</Name>
		<Birthday>1991-01-18</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100003</ID>
		<Name>daria joura</Name>
		<Birthday>1990-05-02</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100004</ID>
		<Name>emily little</Name>
		<Birthday>1994-03-29</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100005</ID>
		<Name>lauren mitchell</Name>
		<Birthday>1991-07-23</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100006</ID>
		<Name>monette russo</Name>
		<Birthday>1988-08-04</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100007</ID>
		<Name>lisa skinner</Name>
		<Birthday>1981-02-17</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100008</ID>
		<Name>allana slater</Name>
		<Birthday>1984-04-03</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>australia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100009</ID>
		<Name>yulia inshina</Name>
		<Birthday>1995-04-15</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>azerbaijan</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100010</ID>
		<Name>anna pavlova</Name>
		<Birthday>1987-09-06</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>azerbaijan</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100011</ID>
		<Name>svetlana boguinskaya</Name>
		<Birthday>1973-02-19</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>belarus</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100012</ID>
		<Name>nellie kim</Name>
		<Birthday>1957-07-29</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>belarus</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100013</ID>
		<Name>olga korbut</Name>
		<Birthday>1955-05-16</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>belarus</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100014</ID>
		<Name>rebeca andrade</Name>
		<Birthday>1999-05-08</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>brazil</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100015</ID>
		<Name>jade barbosa</Name>
		<Birthday>1991-07-01</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>brazil</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100016</ID>
		<Name>daniele hyp�lito</Name>
		<Birthday>1984-09-08</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>brazil</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100017</ID>
		<Name>lorrane oliveira</Name>
		<Birthday>1998-04-13</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>brazil</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100018</ID>
		<Name>daiane dos santos</Name>
		<Birthday>1983-02-10</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>brazil</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100019</ID>
		<Name>fl�via saraiva</Name>
		<Birthday>1999-09-30</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>brazil</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100020</ID>
		<Name>ellie black</Name>
		<Birthday>1995-08-09</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>canada</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100021</ID>
		<Name>elyse hopfner-hibbs</Name>
		<Birthday>1989-09-12</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>canada</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100022</ID>
		<Name>victoria moors</Name>
		<Birthday>1996-11-05</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>canada</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100023</ID>
		<Name>kate richardson</Name>
		<Birthday>1984-06-27</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>canada</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100024</ID>
		<Name>elfi schlegel</Name>
		<Birthday>1964-05-17</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>canada</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100025</ID>
		<Name>eva bos�kov�</Name>
		<Birthday/>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>czechoslovakia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100026</ID>
		<Name>v_ra _�slavsk�</Name>
		<Birthday>1942-05-03</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>czechoslovakia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100027</ID>
		<Name>vlasta d_kanov�</Name>
		<Birthday>2009-09-05</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>czechoslovakia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100028</ID>
		<Name>jana komrskov�</Name>
		<Birthday>1983-05-06</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>czechoslovakia</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100029</ID>
		<Name>cheng fei</Name>
		<Birthday>1988-05-29</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100030</ID>
		<Name>deng linlin</Name>
		<Birthday>1992-04-21</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100031</ID>
		<Name>fan ye</Name>
		<Birthday>1986-10-22</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100032</ID>
		<Name>fan yilin</Name>
		<Birthday>1999-11-11</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100033</ID>
		<Name>he kexin</Name>
		<Birthday>1992-01-01</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100034</ID>
		<Name>he ning</Name>
		<Birthday>1990-11-13</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100035</ID>
		<Name>kui yuanyuan</Name>
		<Birthday>1981-06-23</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100036</ID>
		<Name>li li</Name>
		<Birthday>1975-02-26</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100037</ID>
		<Name>li shanshan</Name>
		<Birthday>1996-08-31</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100038</ID>
		<Name>li ya</Name>
		<Birthday>1988-06-13</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100039</ID>
		<Name>liu xuan</Name>
		<Birthday>1979-03-12</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100040</ID>
		<Name>lu li</Name>
		<Birthday/>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100041</ID>
		<Name>jiang yuyuan</Name>
		<Birthday>1991-11-01</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100042</ID>
		<Name>ma yanhong</Name>
		<Birthday/>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100043</ID>
		<Name>mo huilan</Name>
		<Birthday>1979-07-11</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100044</ID>
		<Name>shang chunsong</Name>
		<Birthday>1996-03-18</Birthday>
		<PlaceOfBirth/>
		<Sex/>
		<Nationality>china</Nationality>
		<Weight/>
		<Height/>
		<OlympicParticipations/>
	</Athlete>
	<Athlete>
		<ID>G-100045</ID>
		<Name>sang lan</Name>
		<Birthday/>
		<PlaceOfBirth/>
		<Sex/>
